import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthProvider } from "@/providers/AuthProvider"; // 1. Importar el Provider
import { getSessionUser } from "@/app/actions/auth";     // 2. Importar la acción

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    // 3. Obtener el usuario en el servidor
    const user = await getSessionUser();

    return (
        <html lang="en" className="">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 4. Envolver la app con el AuthProvider y pasar el usuario */}
        <AuthProvider user={user}>
            <TooltipProvider>
                {children}
            </TooltipProvider>
            <Toaster />
        </AuthProvider>
        </body>
        </html>
    );
}